/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'placeOfBirth' : string,
  'status' : Status,
  'created' : Time,
  'principal' : Principal,
  'applicationNumber' : number,
  'professionPhone' : string,
  'previousResidenceCertNumber' : [] | [string],
  'relationToLandlord' : string,
  'dateOfBirth' : string,
  'hasVehicle' : boolean,
  'lastUpdated' : Time,
  'profession' : string,
  'fullName' : string,
  'isContractRenewal' : boolean,
  'nationality' : number,
  'professionAddress' : string,
  'email' : string,
  'propertyOwner' : string,
  'idNumber' : string,
  'address' : string,
  'gender' : number,
  'startOfResidency' : string,
  'currentAddress' : string,
  'isHomeowner' : boolean,
  'phoneNumber' : string,
  'previousApplications' : number,
  'maritalStatus' : [] | [string],
}
export interface ApplicationForm {
  'placeOfBirth' : string,
  'professionPhone' : string,
  'previousResidenceCertNumber' : [] | [string],
  'relationToLandlord' : string,
  'dateOfBirth' : string,
  'hasVehicle' : boolean,
  'profession' : string,
  'fullName' : string,
  'isContractRenewal' : boolean,
  'nationality' : number,
  'professionAddress' : string,
  'email' : string,
  'propertyOwner' : string,
  'idNumber' : string,
  'address' : string,
  'gender' : number,
  'startOfResidency' : string,
  'currentAddress' : string,
  'isHomeowner' : boolean,
  'phoneNumber' : string,
  'previousApplications' : number,
  'maritalStatus' : [] | [string],
}
export type Status = { 'pending' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createApplication' : ActorMethod<[ApplicationForm], number>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getApplicationById' : ActorMethod<[number], Application>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnApplications' : ActorMethod<[], Array<Application>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];