/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationForm = IDL.Record({
  'placeOfBirth' : IDL.Text,
  'professionPhone' : IDL.Text,
  'previousResidenceCertNumber' : IDL.Opt(IDL.Text),
  'relationToLandlord' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'hasVehicle' : IDL.Bool,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'isContractRenewal' : IDL.Bool,
  'nationality' : IDL.Nat8,
  'professionAddress' : IDL.Text,
  'email' : IDL.Text,
  'propertyOwner' : IDL.Text,
  'idNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Nat8,
  'startOfResidency' : IDL.Text,
  'currentAddress' : IDL.Text,
  'isHomeowner' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'previousApplications' : IDL.Nat8,
  'maritalStatus' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Variant({ 'pending' : IDL.Null });
export const Time = IDL.Int;
export const Application = IDL.Record({
  'placeOfBirth' : IDL.Text,
  'status' : Status,
  'created' : Time,
  'principal' : IDL.Principal,
  'applicationNumber' : IDL.Nat32,
  'professionPhone' : IDL.Text,
  'previousResidenceCertNumber' : IDL.Opt(IDL.Text),
  'relationToLandlord' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'hasVehicle' : IDL.Bool,
  'lastUpdated' : Time,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'isContractRenewal' : IDL.Bool,
  'nationality' : IDL.Nat8,
  'professionAddress' : IDL.Text,
  'email' : IDL.Text,
  'propertyOwner' : IDL.Text,
  'idNumber' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Nat8,
  'startOfResidency' : IDL.Text,
  'currentAddress' : IDL.Text,
  'isHomeowner' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'previousApplications' : IDL.Nat8,
  'maritalStatus' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApplication' : IDL.Func([ApplicationForm], [IDL.Nat32], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getApplicationById' : IDL.Func([IDL.Nat32], [Application], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationForm = IDL.Record({
    'placeOfBirth' : IDL.Text,
    'professionPhone' : IDL.Text,
    'previousResidenceCertNumber' : IDL.Opt(IDL.Text),
    'relationToLandlord' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'hasVehicle' : IDL.Bool,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'isContractRenewal' : IDL.Bool,
    'nationality' : IDL.Nat8,
    'professionAddress' : IDL.Text,
    'email' : IDL.Text,
    'propertyOwner' : IDL.Text,
    'idNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Nat8,
    'startOfResidency' : IDL.Text,
    'currentAddress' : IDL.Text,
    'isHomeowner' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'previousApplications' : IDL.Nat8,
    'maritalStatus' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Variant({ 'pending' : IDL.Null });
  const Time = IDL.Int;
  const Application = IDL.Record({
    'placeOfBirth' : IDL.Text,
    'status' : Status,
    'created' : Time,
    'principal' : IDL.Principal,
    'applicationNumber' : IDL.Nat32,
    'professionPhone' : IDL.Text,
    'previousResidenceCertNumber' : IDL.Opt(IDL.Text),
    'relationToLandlord' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'hasVehicle' : IDL.Bool,
    'lastUpdated' : Time,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'isContractRenewal' : IDL.Bool,
    'nationality' : IDL.Nat8,
    'professionAddress' : IDL.Text,
    'email' : IDL.Text,
    'propertyOwner' : IDL.Text,
    'idNumber' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Nat8,
    'startOfResidency' : IDL.Text,
    'currentAddress' : IDL.Text,
    'isHomeowner' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'previousApplications' : IDL.Nat8,
    'maritalStatus' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApplication' : IDL.Func([ApplicationForm], [IDL.Nat32], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getApplicationById' : IDL.Func([IDL.Nat32], [Application], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };