/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApplicationForm {
    placeOfBirth: string;
    professionPhone: string;
    previousResidenceCertNumber?: string;
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus?: string;
}
export interface Application {
    placeOfBirth: string;
    status: Status;
    created: Time;
    principal: Principal;
    applicationNumber: number;
    professionPhone: string;
    previousResidenceCertNumber?: string;
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    lastUpdated: Time;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus?: string;
}
export type Time = bigint;
export enum Status {
    pending = "pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createApplication(application: ApplicationForm): Promise<number>;
    getAllApplications(): Promise<Array<Application>>;
    getApplicationById(applicationNumber: number): Promise<Application>;
    getCallerUserRole(): Promise<UserRole>;
    getOwnApplications(): Promise<Array<Application>>;
    isCallerAdmin(): Promise<boolean>;
}
import type { Application as _Application, ApplicationForm as _ApplicationForm, Status as _Status, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createApplication(arg0: ApplicationForm): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplication(to_candid_ApplicationForm_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplication(to_candid_ApplicationForm_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationById(arg0: number): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationById(arg0);
                return from_candid_Application_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationById(arg0);
            return from_candid_Application_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnApplications();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnApplications();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
}
function from_candid_Application_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth: string;
    status: _Status;
    created: _Time;
    principal: Principal;
    applicationNumber: number;
    professionPhone: string;
    previousResidenceCertNumber: [] | [string];
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    lastUpdated: _Time;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus: [] | [string];
}): {
    placeOfBirth: string;
    status: Status;
    created: Time;
    principal: Principal;
    applicationNumber: number;
    professionPhone: string;
    previousResidenceCertNumber?: string;
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    lastUpdated: Time;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus?: string;
} {
    return {
        placeOfBirth: value.placeOfBirth,
        status: from_candid_Status_n8(_uploadFile, _downloadFile, value.status),
        created: value.created,
        principal: value.principal,
        applicationNumber: value.applicationNumber,
        professionPhone: value.professionPhone,
        previousResidenceCertNumber: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.previousResidenceCertNumber)),
        relationToLandlord: value.relationToLandlord,
        dateOfBirth: value.dateOfBirth,
        hasVehicle: value.hasVehicle,
        lastUpdated: value.lastUpdated,
        profession: value.profession,
        fullName: value.fullName,
        isContractRenewal: value.isContractRenewal,
        nationality: value.nationality,
        professionAddress: value.professionAddress,
        email: value.email,
        propertyOwner: value.propertyOwner,
        idNumber: value.idNumber,
        address: value.address,
        gender: value.gender,
        startOfResidency: value.startOfResidency,
        currentAddress: value.currentAddress,
        isHomeowner: value.isHomeowner,
        phoneNumber: value.phoneNumber,
        previousApplications: value.previousApplications,
        maritalStatus: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.maritalStatus))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
}): Status {
    return "pending" in value ? Status.pending : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationForm_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationForm): _ApplicationForm {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth: string;
    professionPhone: string;
    previousResidenceCertNumber?: string;
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus?: string;
}): {
    placeOfBirth: string;
    professionPhone: string;
    previousResidenceCertNumber: [] | [string];
    relationToLandlord: string;
    dateOfBirth: string;
    hasVehicle: boolean;
    profession: string;
    fullName: string;
    isContractRenewal: boolean;
    nationality: number;
    professionAddress: string;
    email: string;
    propertyOwner: string;
    idNumber: string;
    address: string;
    gender: number;
    startOfResidency: string;
    currentAddress: string;
    isHomeowner: boolean;
    phoneNumber: string;
    previousApplications: number;
    maritalStatus: [] | [string];
} {
    return {
        placeOfBirth: value.placeOfBirth,
        professionPhone: value.professionPhone,
        previousResidenceCertNumber: value.previousResidenceCertNumber ? candid_some(value.previousResidenceCertNumber) : candid_none(),
        relationToLandlord: value.relationToLandlord,
        dateOfBirth: value.dateOfBirth,
        hasVehicle: value.hasVehicle,
        profession: value.profession,
        fullName: value.fullName,
        isContractRenewal: value.isContractRenewal,
        nationality: value.nationality,
        professionAddress: value.professionAddress,
        email: value.email,
        propertyOwner: value.propertyOwner,
        idNumber: value.idNumber,
        address: value.address,
        gender: value.gender,
        startOfResidency: value.startOfResidency,
        currentAddress: value.currentAddress,
        isHomeowner: value.isHomeowner,
        phoneNumber: value.phoneNumber,
        previousApplications: value.previousApplications,
        maritalStatus: value.maritalStatus ? candid_some(value.maritalStatus) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
